apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-bank-api-deployment
  labels:
    app: simple-bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-bank-api
  template:
    metadata:
      labels:
        app: simple-bank-api
    spec:
      containers:
      - name: simple-bank-api
        image: 007885147968.dkr.ecr.eu-north-1.amazonaws.com/simplebank:885b434b043e84f95cb255b2ca99206a5b853e39
        ports:
        - containerPort: 8080
