name: Deploy to production

on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    name: Build image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3
    # Add the below Kubectl step only when you want to do automatic deployment to Kubernetes with Github action.
    - name: Install Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.29.0' # default is latest stable
      id: install

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-to-assume: ${{ secrets.AWS_ECR_ROLE_ARN }}
        aws-region: eu-north-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Load secrets and save to app.env
      run: aws secretsmanager get-secret-value --secret-id simple_bank --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' >app.env

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: simplebank
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -t $REGISTRY/$REPOSITORY:latest .
        docker push -a $REGISTRY/$REPOSITORY

    # Add the below step when you want to deploy the docker image from ECR to EKS cluster.
    - name: Update Kube config
      run: aws eks update-kubeconfig --name simple-bank --region eu-north-1

    - name: Deploy image
      run: |
        kubectl apply -f eks/aws-auth.yml
        kubectl apply -f eks/deployment.yml
        kubectl apply -f eks/service.yml
        kubectl apply -f eks/issuer.yml
        kubectl apply -f eks/ingress.yml
